# fly.toml app configuration file generated for wild-water-7379 on 2023-05-08T04:14:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-water-7379"
primary_region = "sea"

[http_service]
  internal_port = 3000 
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
